theme: jekyll-theme-slate
title: Cubically's Docs
show_downloads: true
github:
  zip_url: https://github.com/aaronryank/Cubically/archive/master.zip
  tar_url: https://github.com/aaronryank/Cubically/archive/master.tar.gz
